# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "generic/debian10"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
    vb.cpus = "2"
    vb.linked_clone = true
    vb.customize ['modifyvm', :id, '--audio', 'none']
  end
  
  boxes = [
    { :name => "ansible-tower", :ip => "192.168.1.20" },
    { :name => "master", :ip => "192.168.1.21" },
    { :name => "node1", :ip => "192.168.1.22" },
    { :name => "node2", :ip => "192.168.1.23" },
    { :name => "node3", :ip => "192.168.1.24" },
  ]
  
  boxes.each_with_index do |opts, index|
    config.vm.define opts[:name] do |config|
      config.vm.hostname = opts[:name]
      config.vm.network :private_network, ip: opts[:ip]
      config.vm.provision "shell", path: "provision.sh"
    end
  end
  
end